spring.application.name=Helloworld

spring.data.mongodb.uri=mongodb+srv://crud-java:sThbNrualwCep0Os@cluster0.kqt2vhf.mongodb.net/?appName=Cluster0

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

spring.main.allow-bean-definition-overriding=true

# Old H2 config - comment/remove when using MongoDB
# spring.datasource.url=jdbc:h2:mem:tododb
# spring.database.driverClassName=org.h2.Driver
# spring.datasource.username=admin
# spring.datasource.password=1234
# spring.h2.console.enabled=true
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update


